"""second  Migration

Revision ID: 632515cad6ce
Revises: 203861241732
Create Date: 2019-03-01 18:04:40.191426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632515cad6ce'
down_revision = '203861241732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogposts', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogposts', 'title')
    # ### end Alembic commands ###
